### ISSUE TITLE
Wien ist nicht in Wien, und nicht unterteilt in Bezirke

### ISSUE THREAD

**Issue by blackgis** [julian-blaschke/corona-map-austria#1]
Hallo,
Da scheint es ein kleines Problem zu geben mit der Karte oder die lat/lon sind zu ungenau (Nachkommastellen sollten min 6 sein, Genauigkeit von 1m)
![image](https://user-images.githubusercontent.com/7139491/80985175-24c94a00-8e2f-11ea-83fd-77bc172abdc7.png)

Laut [Artikel](https://futurezone.at/digital-life/neue-karte-zeigt-anzahl-der-corona-faelle-pro-bezirk/400831418) sollen es ja pro Bezirk sein, Wien hat 23, also stimmt die Darstellung so nicht ganz mE und Wien sollte in die 23 Bereiche unterteilt werden.

**Comment by julian-blaschke** [comment]
Hi, 
@blackgis Danke für den Hinweis - Wien sollte jetzt an der richtigen Position sein.

Was die Unterteilung in Bezirke von Wien angeht gebe ich Ihnen vollkommen recht, jedoch ist in dem von https://www.data.gv.at/covid-19/ zur Verfügung gestellten Katalog 
> COVID-19: Anzahl der Fälle je Bezirk
nur ein Datensatz für "Wien" vorhanden.
